/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee.management.system;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Asus
 */
public class progressbar extends javax.swing.JFrame {

    /**
     * Creates new form progressbar
     */
    JLabel label = new JLabel();
    
    public progressbar() {
       
        initComponents();
        getContentPane().setBackground(Color.white);//bacgrndcolor
        setLayout(null);
        
        label.setBounds(0,0,1000,1000);
        label.setFont(new Font("Arial",Font.PLAIN,18));
        label.setForeground(Color.WHITE);//label text color
        jLabel1.add(label);
        ImageIcon p1 = new ImageIcon(ClassLoader.getSystemResource("pics/entry4.jpg"));
        Image i=p1.getImage().getScaledInstance(750,800, Image.SCALE_DEFAULT);
        ImageIcon p2= new ImageIcon(i);
        JLabel image =new JLabel(p2);
        image.setBounds(0,0,750,750);
        jLabel1.add(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadingValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LosdingBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setForeground(new java.awt.Color(0, 51, 51));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 300, 20));

        ImageIcon p1 = new ImageIcon(ClassLoader.getSystemResource("pics/entry4.jpg"));
        Image i=p1.getImage().getScaledInstance(2000,1000, Image.SCALE_DEFAULT);
        ImageIcon p2= new ImageIcon(i);
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 560));

        LosdingBar.setBackground(new java.awt.Color(0, 51, 51));
        LosdingBar.setForeground(new java.awt.Color(0, 51, 51));
        LosdingBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        LosdingBar.setBorderPainted(false);
        LosdingBar.setOpaque(true);
        getContentPane().add(LosdingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 558, 740, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(progressbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(progressbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(progressbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(progressbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        progressbar s= new progressbar();
        s.setVisible(true);
        try{
            for(int i=0;i<=100;i++)
            {
                Thread.sleep(20);
                s.LoadingValue.setText(i+"%");
               if(i==10)
               {
                   s.label.setText("Loading components...");
               }
                if(i==20)
               {
                   s.label.setText("Loading modules...");
               }
                 if(i==40)
               {
                   s.label.setText("Authenticating...");
               }
                  if(i==60)
               {
                   s.label.setText("Acessing database...");
               }
               if(i==80)
               {
                   s.label.setText("Loading Graphics...");
               }
               if(i==90)
               {
                   s.label.setText("Ready...");
               }
                
                 s.LosdingBar.setValue(i);
            }
        }
            catch(Exception e)
                    {}
        
        s.dispose();
        new entry().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LoadingValue;
    private javax.swing.JProgressBar LosdingBar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
